### ISSUE TITLE
vagrant group <group> destroy -f exits on error

### ISSUE THREAD

**Issue by jhcook** [krzysztof-magosa/vagrant-group#1]
The "-f" option to destroy causes an error and exit. This is inconvenient for groups with several machines.

**Comment by krzysztof-magosa** [comment]
At the moment `vagrant-group` does not support parameters. I'm doing analysis how to approach that, because I don't want to reinvent the wheel by reimplementing all of them. Ideally would be to pass parameters to original mechanism so it can validate them etc.

**Comment by krzysztof-magosa** [comment]
I've added ability to use `-f` or `--force` in `halt` and `destroy` commands.
