### ISSUE TITLE
Interface should be more similar to Vagrant default

### ISSUE THREAD

**Issue by jhcook** [krzysztof-magosa/vagrant-group#4]
In Vagrant, one can manipulate machines by something like:

`vagrant up /dns/`

The same in vagrant-group is:

`vagrant group dns up`

Shouldn't it be `vagrant group up dns`?

Also, it would be nice to have regex for group names so if you had a group for internaldns and externaldns you could do:

`vagrant group up /dns/`

**Comment by krzysztof-magosa** [comment]
Yes, I agree - it would be more natural.

**Comment by krzysztof-magosa** [comment]
I reversed order of parameters to be compatible with vagrant style.
For regex I created separate ticket #6.
